export enum InternalErrorCode {
  // Auth : 1 ~ 50,
  AUTH_USER_MISMATCHED_PASSWORD = 1,
  // User : 51 ~ 100
  USER_NOT_FOUND = 51,
  USER_ALREADY_CREATED = 52,
  USER_UPDATE_FAIL = 53,
  USER_BLOCK = 54,
  USER_NICKNAME_ALREADY_USED = 55,
  USER_NICKNAME_UPDATE_FAILED = 56,
  USER_DELETE_FAILED = 57,
  USER_EMAIL_ALREADY_USED = 58,
  USER_ALREADY_LOGOUT = 59,
}
